### ISSUE TITLE
What is this? :)

### ISSUE THREAD

**Issue by ghost** [HappyCord/Discord-Integration#1]
Can you add a readme, explaining what this project actually is? It seems quite interesting to add to my server, but I have no clue what it really is.
From what I can understand, it looks like an announcements plugin for spigot, is that right?

**Comment by OakleyCord** [comment]
sorry for not responding after 10 hours but this plugin is unfinished and I should have privated it until it was polished and had a readme but its a plugin that sends messages of in-game chat from server to a discord channel also allows for people to interact with each other

Leaving/Joining example  (Screenshot of it being used on an smp I am in):
![image](https://user-images.githubusercontent.com/66735773/129837730-2ec9ef30-bccf-4566-9ce0-eddaaf5c13bd.png)

Chatting example (Screenshot of it being used on an smp I am in):
![image](https://user-images.githubusercontent.com/66735773/129837970-689172cd-f30b-4fc2-a742-67833ac3c5e7.png)

It also has some commands:
![image](https://user-images.githubusercontent.com/66735773/129838149-7a01ff36-9adc-4e07-a38f-e44b51841ecc.png)

hope that clears this up for you

**Comment by OakleyCord** [comment]
this is also (kinda) my first time using github and i am loving this  :)

**Comment by ghost** [comment]
Seems awesome, I'll be definitely on the lookout! Welcome to Github!
Btw, you are the top result on Duckduckgo when you search for ``GitHub integration discord``.
Good luck with your project!
You can change your repo visibility here: https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/setting-repository-visibility :).
